name: gamini_ai_chat
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # ui
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10

  # api
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  
  image_picker: ^1.0.7
  intl: ^0.19.0
  uuid: ^4.3.3
  google_fonts: ^6.1.0
  gap: ^3.0.1
  get: ^4.6.6
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_native_splash: ^2.3.9
  google_sign_in: ^6.2.1
  line_awesome_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
